config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :authorisations, only: [:index, :show, :create, :update] do
    get :giving, on: :collection
    post :give, on: :collection
  end
  get 'authorisation/requesting', to: 'authorisations#requesting', as: 'authorisation_request'
  get 'authorisation/grant', to: 'authorisations#granting'
  
  resources :threads, only: [:show]
  post 'threads/update_tags'
  
  resources :attachment, only: [:show] do
  	get :download_inline, on: :collection
  end

  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    resources :users, only: [:index, :show]
    resources :authorisations, only: [:index]
    resources :delegations, only: [:index]
  end

  resources :delegations, only: [:index, :new, :create] do
    get :confirm
    get :revoke
    get :cancel
  end
end

app/models/delegation.rb
class Delegation < ActiveRecord::Base
	include Tokenable

	belongs_to :manager, class_name: 'User'
	belongs_to :employee, class_name: 'User'
	validates :manager_id, presence: true
	validates :employee_id, presence: true
	attr_accessor :employee_email, :description
	scope :active, -> { where(:is_active => true) }

	def activate
		Delegation.deactivate_all(self)
		self.update(is_active: true)
		DelegationMailer.confirm_delegation(self).deliver
	end

	def deactivate(role)
		if self.is_active #only email if it's currently active
			DelegationMailer.revoke_delegation(self).deliver if role == 'employee'
			DelegationMailer.cancel_delegation(self).deliver if role == 'manager'
		end
		self.update(is_active: false)
	end

	# Deactivate any other active delegation for that employee
	def self.deactivate_all(active_delegation)
		active_delegation.employee.employee_delegations.active.each do |delegation|
			delegation.deactivate('employee')
		end
	end

	def status
		self.is_active ? 'active' : 'not active'
	end
end

app/controllers/admin/delegations_controller.rb
class Admin::DelegationsController < ApplicationController
  before_action :logged_in_admin
  layout 'admin'
  
  def index
  	@delegations = Delegation.order('id desc').all.paginate(page: params[:page])
  	respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/delegations_controller.rb
class DelegationsController < ApplicationController
  before_action :logged_in_user
  before_action :is_manager, only: [:index, :new, :create, :cancel]

  def index
  	@delegations = current_user.managed_delegations.order('created_at desc').all.paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
  	@delegation = current_user.managed_delegations.new
  end

  def create
  	@delegation = current_user.managed_delegations.new(delegation_params)
    employee = User.find_or_create_guest(params['delegation']['employee_email'])
    unless employee.nil?
      @delegation.employee_id = employee.id
      delegation_db = Delegation.find_by(manager_id: current_user.id, employee_id: @delegation.employee_id)
      @delegation = delegation_db if delegation_db #select existing delegation if it already exists for this manager + employee
    end
    if @delegation.save
      DelegationMailer.request_delegation(@delegation).deliver
      flash[:notice] = 'Request sent!'
      redirect_to delegations_path and return
    else
      @delegation.errors.add(:employee_email, :blank) if employee.nil?
      flash[:alert] = 'Something went wrong, try again'
      render 'new'
    end
  end

  # Confirmation (only by employee)
  def confirm
  	@delegation = current_user.employee_delegations.find_by(token: params[:delegation_id])
  	if @delegation.nil?
  		flash[:alert] = 'You are not authorised to access this page'
  		redirect_to root_path and return
  	else
  		@delegation.activate
  		flash[:notice] = 'Request confirmed! Your account is now controlled by ' + @delegation.manager.full_identity
      redirect_to root_path and return
  	end
  end

  # Revoke (only by employee -> mirror of cancel)
  def revoke
    @delegation = current_user.employee_delegations.find_by(token: params[:delegation_id])
    if @delegation.nil?
      flash[:alert] = 'You are not authorised to access this page'
      redirect_to root_path and return
    else
      @delegation.deactivate('employee')
      flash[:notice] = 'Confirmed! Your account is no longer controlled by ' + @delegation.manager.full_identity
      redirect_to root_path and return
    end
  end

   # Cancellation (only by manager -> mirror of revoke)
  def cancel
    @delegation = current_user.managed_delegations.find_by(token: params[:delegation_id])
    if @delegation.nil?
      flash[:alert] = 'You are not authorised to access this page'
      redirect_to delegations_path and return
    else
      @delegation.deactivate('manager')
      flash[:notice] = 'Confirmed! You no longer control the account of ' + @delegation.employee.full_identity
      redirect_to delegations_path and return
    end
  end

  private

    def delegation_params
      params.require(:delegation).permit(:employee_email, :description)
    end
end

app/helpers/admin/delegations_helper.rb
module Admin::DelegationsHelper
end

app/helpers/delegation_helper.rb
module DelegationHelper
end

app/views/delegations/_delegation.html.erb
<div class="panel panel-white">
	<div class="row authorisation-block">
		<div class="col-sm-6">
			<div class="status-disc status-disc-<%= status_meaning(delegation.status) %>" data-toggle="tooltip" data-placement="bottom" title="<%= delegation.status.capitalize %>"></div>
			<span class="person">With <span class="name"><%= delegation.employee.full_identity %></span></span>

		</div>
		<div class="col-sm-3">
			<span class="date">
				<strong class="visible-xs-inline">Date:</strong>
				<%= delegation.created_at.strftime("%d/%m/%y") + ' (' + distance_of_time_in_words(delegation.created_at, Time.now) + ' ago)' %></span>
		</div>
		<div class="col-sm-3">
			<span class="user-actions pull-right">
				<% if delegation.is_active %>
					<%= link_to 'Cancel', delegation_cancel_path(delegation.token), class: 'btn btn-warning' %>
				<% end %>
			</span>
		</div>
	</div>
</div>

app/views/delegations/_employee_revocation.html.erb
<div class="alert alert-danger alert-dismissible" role="alert">
	<button type="button" class="close" data-dismiss="alert">
	  <span aria-hidden="true">&times;</span>
	  <span class="sr-only">close</span>
	</button>
	<%= 'Your account is currently managed by ' + current_user.manager_delegation.manager.full_identity + '. ' %>
	<%= link_to 'click here to revoke it', delegation_revoke_path(current_user.manager_delegation.token), class: 'btn btn-hollow' %>
</div>

app/views/delegations/index.html.erb
<% provide(:title, 'Manage your team') %>
<% if @delegations.any? %>
  <div class="row">
    <div class="col-sm-8"><h1>Manage your team</h1></div>
    <div class="col-sm-4">
      <div class="pull-right">
        <%= link_to 'New delegation', new_delegation_path, class: 'btn btn-primary h1-btn' %>
      </div>
    </div>
  </div>
  <p class="lead">
    Passiton lets your team share context with teammates. As a manager, you can approve requests on their behalf - useful if they go on holiday or leave the company.
  </p>
  <div id="results">
    <%= render partial: 'delegations/delegation', collection: @delegations %>
  </div>
  <% if !@delegations.nil? and @delegations.any? %>
    <div id="infinite-scrolling">
      <%= will_paginate @delegations %>
    </div>
  <% end %>

<% else %>
  <h1>Hi <%= current_user.first_name %>, let's manage your team</h1>
  <p class="lead">
    Passiton lets your team share context with teammates. As a manager, you can approve requests on their behalf - useful if they go on holiday or leave the company.
  </p>
  <div class="row">
    <div class="panel panel-white text-center col-sm-4 col-sm-offset-4">
      <p class="lead">Get started</p>
      <p>Ask a teammate to <br> manage their Passiton account</p>
      <%= link_to 'New delegation', new_delegation_path, class: 'btn btn-primary center-block' %>
    </div>
  </div>
<% end %>

app/views/delegations/index.js.erb
$('#results').append("<%= j render partial: 'delegations/delegation', collection: @delegations %>");
<% if @delegations.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @delegations %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>
initialize();

app/views/delegations/new.html.erb
<% provide(:title, 'Request delegation') %>
<h1>Request delegation</h1>
<p class="lead">
  Ask a teammate to hand over control of their Passiton access sharing to you, for example when they leave the company or go on holiday.
  They can revoke it at any time.
</p>

<div class="panel panel-white">
  <div class="row">
    <div class="col-sm-offset-2 col-xs-12 col-sm-8" >
      <%= simple_form_for @delegation, :url => delegations_path  do |f| %>
      	<%= f.input :employee_email, label: 'Teammate', placeholder: 'Enter the email of your teammate', required: true %>
      	<%= f.input :description, label: 'Personal message', placeholder: 'Dear Patricia, this will let us see the status of your deals during your holiday' %>
        <div class="row">
          <div class="col-xs-9">
          <p>
            Passiton will send an email to your teammate to request their approval.
            <br/>They can revoke this context at any time.
          </p>
          </div>
          <div class="col-xs-3">
        	 <%= f.button :submit, "Send it", :class => 'btn btn-primary pull-right' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>