config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :authorisations, only: [:index, :show, :create, :update] do
    get :giving, on: :collection
    post :give, on: :collection
  end
  get 'authorisation/requesting', to: 'authorisations#requesting', as: 'authorisation_request'
  get 'authorisation/grant', to: 'authorisations#granting'
  
  resources :threads, only: [:show]
  post 'threads/update_tags'
  
  resources :attachment, only: [:show] do
  	get :download_inline, on: :collection
  end

  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    resources :users, only: [:index, :show]
    resources :authorisations, only: [:index]
    resources :delegations, only: [:index]
  end

  resources :delegations, only: [:index, :new, :create] do
    get :confirm
    get :revoke
    get :cancel
  end
end

app/models/authorisation.rb
include ApplicationHelper
include ThreadHelper

class Authorisation < ActiveRecord::Base
	include Tokenable
	
	belongs_to :requester, class_name: 'User'
	belongs_to :granter, class_name: 'User'
	validates :requester_id, presence: true
	validates :granter_id, presence: true
	validates :scope, presence: true
	validates :status, presence: true, inclusion: { in: ['pending', 'granted', 'denied', 'revoked'] }
	attr_accessor :granter_email, :requester_email
	has_many :email_threads
	has_many :message_attachments, through: :email_threads
	has_many :message_participants, through: :email_threads
	has_many :participants, through: :message_participants
	has_many :synchronisation_errors
	has_many :authorisation_searches
  	scope :authorised,  -> { where(:status => 'granted') }
  	scope :uptodate,  -> { where(:synced => true) } # initial sync has been done

	# Launches an asynchronous sync of threads etc. (first_time = true if this is the first sync)
	def sync_job(first_time = false, user = 'requester')
		Rails.logger.info('Authorisation sync job started for scope: ' + self.scope)
		GmailSyncerJob.new.async.perform(self, first_time, user)
	end

	def enabled
		self.status == 'granted'
	end

	# Returns the different statuses the authorisation can move to
	def possible_statuses
		case self.status
		when 'pending'
			['granted', 'denied']
		when 'granted'
			['revoked']
		when 'denied'
			['granted']
		when 'revoked'
			['granted']
		else
			[]
		end
	end

	def update_status(status)
		self.update!(status: status)
		case self.status
		when 'granted'
			if !self.synced
        		Rails.logger.info('Authorisation update_status granted - gmail sync launched from granter')
				self.sync_job(true, 'granter')
			else
				AuthorisationMailer.authorisation_granted(self).deliver
			end
		when 'denied'
			AuthorisationRevokerJob.new.async.perform(self)
			AuthorisationMailer.authorisation_denied(self).deliver
		when 'revoked'
			AuthorisationRevokerJob.new.async.perform(self)
			AuthorisationMailer.authorisation_revoked(self).deliver
		end
	end
end

app/controllers/admin/authorisations_controller.rb
class Admin::AuthorisationsController < ApplicationController
  before_action :logged_in_admin
  layout 'admin'

  def index
  	@authorisations = Authorisation.order('id desc').all.paginate(page: params[:page])
  	respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/authorisations_controller.rb
class AuthorisationsController < ApplicationController
  before_action :logged_in_user

  def index
  	@authorisations = current_user.requested_authorisations.all.order('created_at desc')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
  	# Figuring out the role of the viewer and whether they are authorised to see it (them or their manager)
    @authorisation = Authorisation.find_by(token: params[:id])
    unless @authorisation.nil?
      @viewer_type = 'requester' if current_user == @authorisation.requester or (!@authorisation.requester.manager_delegation.nil? && current_user == @authorisation.requester.manager_delegation.manager)
      @viewer_type = 'granter' if @viewer_type.nil? and (current_user == @authorisation.granter or (!@authorisation.granter.manager_delegation.nil? && current_user == @authorisation.granter.manager_delegation.manager))
      # Handling the case of someone requesting from themselves
      if !@viewer_type.nil? and @authorisation.requester_id == @authorisation.granter_id
        if @authorisation.enabled
          @viewer_type = 'requester'
        else
          @viewer_type = 'granter'
        end
      end
    end

  	if @authorisation.nil? or @viewer_type.nil? or (!@authorisation.enabled and @viewer_type == 'requester') or !@authorisation.synced
      flash[:alert] = "Either you are not authorised anymore or it hasn't finished syncing"
  		redirect_to authorisations_path and return
  	end

  	tab_selected = !params['tab_filter'].nil?
    params[:tab_filter] = 'highlight' if params['tab_filter'].nil? # default tab
    @tab_filter = params[:tab_filter]
    params_filters = params.slice(:tab_filter)

    # Handling searches
    if params['search'] and !params['search'].blank?
      @search = @authorisation.authorisation_searches.find_by(scope: params['search'])
      @search = @authorisation.authorisation_searches.create(scope: params['search']) if @search.nil?
      @tab_filter = 'search'
      Rails.logger.info('Auth search started for scope: ' + @authorisation.scope + ' ' + params['search'] + ' and id: ' + @authorisation.id.to_s)
      found_threads = GmailSync.search_threads(@authorisation, @search)
      Rails.logger.info('Auth search completed for scope: ' + @authorisation.scope + ' ' + params['search'] + ' and id: ' + @authorisation.id.to_s + ' with found thread count: ' + found_threads.count.to_s)
      @threads = @authorisation.email_threads.by_latest_email.joins(:tags).where(synced: true).where(thread_id: found_threads).includes(:message_attachments, :message_participants, :participants).distinct.all.paginate(page: params[:page], :per_page => 10)
    elsif @tab_filter == 'authorisation_participants'
      @participants_from_scope = Participant.from_scope(@authorisation.scope, @authorisation)
    elsif @tab_filter == 'authorisation_attachments'
      @attachments = @authorisation.message_attachments.order('email_date DESC').all
      @attachments_grouped = {}
      @attachments.each do |attachment|
        @attachments_grouped[attachment.type_group] ||= []
        @attachments_grouped[attachment.type_group].push(attachment)
      end
    else
      if !tab_selected and @authorisation.email_threads.joins(:tags).where(synced: true).filter(params_filters).empty?
        params[:tab_filter] = 'all'
        @tab_filter = 'all'
        params_filters = params.slice(:tab_filter)
      end
      @threads = @authorisation.email_threads.by_latest_email.joins(:tags).where(synced: true).filter(params_filters).includes(:message_attachments, :message_participants, :participants).distinct.all.paginate(page: params[:page], :per_page => 10)
    end

    @searches = @authorisation.authorisation_searches.order('id desc').limit(5).all

    @container = false
    respond_to do |format|
      format.html
      format.js
    end
  end

  def requesting
    @authorisation = Authorisation.new
  end

  def granting
    @authorisations = current_user.granted_authorisations.all.order('created_at desc')
    respond_to do |format|
      format.html
      format.js
    end
  end

  # create authorisation from requester
  def create
    @authorisation = Authorisation.new(authorisation_params)
    @authorisation.requester_id = current_user.id
    granter = User.find_or_create_guest(params['authorisation']['granter_email'])
    unless granter.nil?
      @authorisation.granter_id = granter.id
    end
    @authorisation.status = 'pending'
    if @authorisation.save
      if !@authorisation.granter.guest
        Rails.logger.info('Auth controller create - gmail sync launched from requester')
        @authorisation.sync_job(true, 'requester') # Get started syncing the authorisation
      else
        AuthorisationMailer.request_authorisation(@authorisation).deliver # Email the granter since we can't sync with guests
      end
      flash[:notice] = 'Context requested!'
      redirect_to authorisations_path and return
    else
      @authorisation.errors.add(:granter_email, :blank) if granter.nil?
      flash[:alert] = 'Something went wrong, try again'
      render 'requesting'
    end
  end

  def update
    @authorisation = Authorisation.find_by(token: params[:id])
    if !@authorisation.nil? and User.can_access([@authorisation.granter.id], current_user.id)
      @authorisation.update_status(params['authorisation']['status'])
      redirect_to authorisation_grant_path and return
    else
      flash[:alert] = 'Something went wrong, try again'
      redirect_to authorisation_grant_path and return
    end
  end

  def giving
    @authorisation = Authorisation.new
  end

  # create authorisation from granter
  def give
    @authorisation = Authorisation.new(authorisation_params)
    @authorisation.granter_id = current_user.id
    requester = User.find_or_create_guest(params['authorisation']['requester_email'])
    unless requester.nil?
      @authorisation.requester_id = requester.id
    end
    @authorisation.status = 'granted'
    if @authorisation.save
      Rails.logger.info('Auth controller give - gmail sync launched from granter')
      @authorisation.sync_job(true, 'granter') # Get started syncing the authorisation
      flash[:notice] = 'Context given!'
      redirect_to authorisation_grant_path and return
    else
      @authorisation.errors.add(:requester_email, :blank) if requester.nil?
      flash[:alert] = 'Something went wrong, try again'
      render 'giving'
    end
  end

  private

    def authorisation_params
      params.require(:authorisation).permit(:scope, :description)
    end
end

app/helpers/admin/authorisations_helper.rb
module Admin::AuthorisationsHelper
end

app/helpers/authorisation_helper.rb
module AuthorisationHelper
end

app/views/authorisations/_attachment.html.erb
<% if !attachment.inline %>
  <li>
    <% if !attachment.filename.empty?  %>
      <span class="<%= glyphicon_file(attachment.type) %>" aria-hidden="true"></span>
      <a href="<%= attachment_path(attachment) %>"><%= attachment.filename %></a>
      <%= attachment.email_date.strftime("%d %b") %>
    <% end %>
  </li>
<% end %>

app/views/authorisations/_authorisation.html.erb
<div class="panel panel-white">
	<div class="row authorisation-block <%= (!authorisation.synced or !authorisation.enabled) ? 'refresh-authorisation-status' : '' %>">
		<div class="col-sm-6 col-xs-12">
			<span class="person">With <span class="name"><%= authorisation.granter.email %></span></span>
			<span class="date"><%= authorisation.created_at.strftime("%d/%m/%y") + ' (' + distance_of_time_in_words(authorisation.created_at, Time.now) + ' ago)' %></span>
		</div>
		<div class="col-sm-6 col-xs-12">
			<div class="status-disc status-disc-<%= status_meaning(authorisation.status) %>" data-toggle="tooltip" data-placement="bottom" title="<%= authorisation.status.capitalize %>"></div>
			<strong><span class="scope">
				<% if authorisation.synced & authorisation.enabled %>
				<%= link_to authorisation.scope, authorisation_path(authorisation.token) %>
				<% else %>
					<%= authorisation.scope %>
				<% end %>
			</span></strong>
			<span class="count">
				<% if authorisation.synced & authorisation.enabled %>
					<%= authorisation.email_threads.count %>
					<span class="glyphicon glyphicon-list"></span>
				<% end %>
			<span>
			<span class="user-actions pull-right">
				<% if authorisation.synced & authorisation.enabled %>
					<%= link_to 'View', authorisation_path(authorisation.token), class: 'btn btn-default' %>
				<% elsif authorisation.enabled %>
					<%= image_tag 'ajax-loader.gif', alt: 'Loading...', title: 'Loading...' %>
				<% end %>
			</span>
		</div>
	</div>
</div>

app/views/authorisations/_participant.html.erb
<div class="panel panel-white">
  <div class="row">
    <div class="col-sm-4">
        <strong class="visible-xs-inline">Name:</strong>
        <%= participant.first_name %> <%= participant.last_name %>
    </div>
    <div class="col-sm-5">
        <strong class="visible-xs-inline">Email:</strong>
        <%= participant.email %>
    </div>
    <div class="col-sm-3">
        <strong class="visible-xs-inline">Company:</strong>
        <%= participant.company.titleize %>
    </div>
  </div>
</div>

app/views/authorisations/_requested_authorisation.html.erb
<div class="panel panel-white">
	<div class="row authorisation-block">
		<div class="col-sm-6 col-xs-12">
			<span class="person">With <span class="name"><%= requested_authorisation.requester.full_identity %></span></span>
			<span class="date"><%= requested_authorisation.created_at.strftime("%d/%m/%y") + ' (' + distance_of_time_in_words(requested_authorisation.created_at, Time.now) + ' ago)' %></span>
		</div>
		<div class="col-sm-3 col-xs-12">
			<div class="status-disc status-disc-<%= status_meaning(requested_authorisation.status) %>" data-toggle="tooltip" data-placement="bottom" title="<%= requested_authorisation.status.capitalize %>"></div>
				<strong><span class="scope"><%= requested_authorisation.scope %></span></strong>
				<span class="count">
					<%= requested_authorisation.email_threads.count %>
					<span class="glyphicon glyphicon-list"></span>
				<span>
		</div>
		<div class="col-sm-3 col-xs-12">
			<span class="clearfix">
				<% requested_authorisation.possible_statuses.each do |possible_status| %>
					<div class="pull-right">
						<%= simple_form_for requested_authorisation, :url => authorisation_path(requested_authorisation.token) do |f| %>
						<%= f.input :status, as: :hidden, :input_html => { value: possible_status } %>
						<% if possible_status == 'granted' %>
							<%= f.button :submit, "Grant", :class => 'btn-success btn-margin' %>
						<% elsif possible_status == 'revoked' %>
							<%= f.button :submit, "Revoke", :class => 'btn-warning btn-margin' %>
						<% elsif possible_status == 'denied' %>
							<%= f.button :submit, "Deny", :class => 'btn-primary btn-margin' %>
						<% end %>
					<% end %>
					</div>
				<% end %>
				<% if !['denied', 'revoked'].include? requested_authorisation.status %>
					<% if !requested_authorisation.synced %>
						<button type="button" disabled="disabled" class="btn-link pull-right btn-margin">
							<%= image_tag 'ajax-loader.gif', alt: 'Loading...', title: 'Loading...' %>
						Preview
						</button>
					<% else %>
						<a href="<%= authorisation_path(requested_authorisation.token) %>" class="btn btn-default btn-margin pull-right <%= 'refresh-authorisation-status' %>"> 
						<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Preview
						</a>		
					<% end %>	
				<% end %>
			</span>
		</div>
	</div>
</div>

app/views/authorisations/_thread.html.erb
<% if !(@viewer_type == 'requester' and thread.is_hidden?) %>
  <div class="panel panel-white panel-tight panel-clickable">
    <div class="row timeline">

      <!-- Thread emails launcher -->
      <a class="thread-action" data-role="thread-email-link" data-path="<%= thread_url(thread) %>">
        <span></span>
      </a>

      <div class="col-xs-1 col-sm-1 col-md-1">
        <% if @viewer_type == 'requester' %>
          <form action="<%= threads_update_tags_path %>" method="post" data-remote="true" class="form-highlight">
            <input type="hidden" name="thread_id" value="<%= thread.id %>">
            <input type="hidden" name="tag_type" value="highlight">
            <div class="checkbox hide">
              <label><input type="checkbox" name="tag_highlight" <%= 'checked="checked"' if thread.is_highlighted? %> class="checkbox-highlight" id="checkbox-highlight-<%= thread.id %>">&nbsp;<%= thread.id %></label>
            </div>
            <a href="" data-action="toggle-checkbox" data-target="#checkbox-highlight-<%= thread.id %>">
              <span class="glyphicon glyphicon-lg glyphicon-pushpin glyphicon-click <%= thread.is_highlighted? ? 'active' : 'inactive' %>" aria-hidden="true" data-role="checkbox-indicator" data-toggle="tooltip" data-placement="right" title="Tag a thread as highlight to easily find it again"></span>
            </a>
          </form>
        <% elsif @viewer_type == 'granter' %>
          <form action="<%= threads_update_tags_path %>" method="post" data-remote="true" class="form-highlight">
            <input type="hidden" name="thread_id" value="<%= thread.id %>">
            <input type="hidden" name="tag_type" value="hide">
            <div class="checkbox hide">
              <label><input type="checkbox" name="tag_hide" <%= 'checked="checked"' if thread.is_hidden? %> class="checkbox-hide" id="checkbox-hide-<%= thread.id %>">&nbsp;<%= thread.id %></label>
            </div>
            <a href="" data-action="toggle-checkbox" data-target="#checkbox-hide-<%= thread.id %>">
              <span class="glyphicon glyphicon-lg glyphicon-remove glyphicon-click <%= thread.is_hidden? ? 'active' : 'inactive' %>" aria-hidden="true" data-role="checkbox-indicator" data-toggle="tooltip" data-placement="right" title="Hide from requester"></span>
            </a>
          </form>
        <% end %>
        <% if !thread.message_attachments.not_inline.empty? %>
          <a data-role="trigger-toggle-display" data-target="#attachments-thread-<%= thread.id %>">
            <span class="glyphicon glyphicon-paperclip glyphicon-click" aria-hidden="true"></span>
          </a>
        <% end %>
      </div>
      <div class="col-xs-11 col-sm-11 col-md-11">
        <div class="row">
          <div class="col-xs-9 col-sm-9 col-md-9">
            <p>
              <% thread.readable_labels.each do |label| %>
                <%= glyphicon_label(label).html_safe %>
              <% end %>
              <b><%= thread.subject %></b>
              <% if thread.email_count > 1 %>
                <span class="badge"><%= thread.email_count %></span>
              <% end %>
            </p>
          </div>
          <div class="col-xs-3 col-sm-3 col-md-3">
            <p class="text-right"><%= thread.latest_email_date.strftime("%d %b") %></p>
          </div>
        </div>
        <p>
          <%= thread.unique_senders.map { |p| p.first_name + ' ' + p.last_name + ' <small class="hidden-xs">(' + p.company + ')</small>'}.join(', ').html_safe %>
          <br>
          <small class="no-ellipsis-mobile"><%= thread.snippet.html_safe %></small>
        </p>
        <% if !thread.message_attachments.not_inline.empty? %>
          <div id="attachments-thread-<%= thread.id %>" class="hide attachment">
            <ul class="list-unstyled">
              <%= render partial: 'authorisations/attachment', collection: thread.message_attachments.not_inline %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/authorisations/giving.html.erb
<% provide(:title, 'Give context') %>
<h1>Give context</h1>
<p class="lead">
  Share specific emails with a teammate.
</p>

<div class="panel panel-white">
  <div class="row">
    <div class="col-sm-offset-2 col-xs-12 col-sm-8" >
      <%= simple_form_for @authorisation, :url => give_authorisations_path  do |f| %>
        <%= f.input :scope, label:'Context', autofocus: true, placeholder: 'Same as a Gmail or Google search (Apple, steve@apple.com...)' %>
      	<%= f.input :requester_email, label: 'Teammate', placeholder: 'Enter the email of your teammate', required: true %>
      	<%= f.input :description, label: 'Personal message', placeholder: 'Hey John, I\'d like to get you up to speed on my client' %>
        <div class="row">
          <div class="col-xs-9">
            <p>
              Passiton will send an email to your teammate to share context.
              <br/>You can revoke this context at any time.
            </p>
          </div>
          <div class="col-xs-3">
            <%= f.button :submit, "Send it", :class => 'btn btn-primary pull-right' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/authorisations/granting.html.erb
<% provide(:title, 'Give context') %>
<div class="row">
  <div class="col-sm-8"><h1>Give context</h1></div>
  <div class="col-sm-4">
    <div class="pull-right">
      <%= link_to 'Give context', giving_authorisations_path, class: 'btn btn-primary h1-btn' %>
    </div>
  </div>
</div>
<p class="lead">
  Approve, deny or revoke requests for context from your teammates.
</p>

<% if @authorisations.any? %>
	<div id="results" data-target="<%= authorisation_grant_path %>">
    <%= render partial: 'authorisations/requested_authorisation', collection: @authorisations %>
  </div>

<% else %>
  <div class="row">
    <div class="panel panel-white text-center col-sm-4 col-sm-offset-1">
      <p class="lead">Keep asking</p>
      <p>Ask a teammate to see<br> specific emails</p>
      <%= link_to 'Get context', authorisation_request_path, class: 'btn btn-primary center-block' %>
    </div>
    <div class="panel panel-white text-center col-sm-4 col-sm-offset-1">
      <p class="lead">Start sharing</p>
      <p>Let a teammate see<br> specific emails</p>
      <%= link_to 'Give context', giving_authorisations_path, class: 'btn btn-primary center-block' %>
    </div>
  </div>

<% end %>

app/views/authorisations/index.html.erb
<% provide(:title, 'Get context') %>
<% if @authorisations.any? %>
  <div class="row">
    <div class="col-sm-8"><h1>Get context</h1></div>
    <div class="col-sm-4">
      <div class="pull-right">
        <%= link_to 'Get context', authorisation_request_path, class: 'btn btn-primary h1-btn' %>
      </div>
    </div>
  </div>
  <p class="lead">
    Context you've requested from your teammates. All in one place.
  </p>
  <div id="results" data-target="<%= authorisations_path %>">
    <%= render partial: 'authorisations/authorisation', collection: @authorisations %>
  </div>

<% else %>

  <div class="row">
    <div class="col-sm-12">
      <h1>Hi <%= current_user.first_name %>, welcome to Passiton</h1>
      <p class="lead">
        Passiton lets you share context with teammates. Let's get you started.
      </p>
    </div>
  </div>
  
  <div class="row">
    <div class="panel panel-white text-center col-sm-4 col-sm-offset-1">
      <p class="lead">It's me time</p>
      <p>Ask a teammate to see<br> specific emails</p>
      <%= link_to 'Get context', authorisation_request_path, class: 'btn btn-primary center-block' %>
    </div>
    <div class="panel panel-white text-center col-sm-4 col-sm-offset-2">
      <p class="lead">I'm feeling generous</p>
      <p>Let your teammate see<br> specific emails</p>
      <%= link_to 'Give context', giving_authorisations_path, class: 'btn btn-primary center-block' %>
    </div>
  </div>

<% end %>

app/views/authorisations/show.html.erb
<% provide(:title, 'Emails about ' + @authorisation.scope) %>
<div class="container-fluid">
  <div class="panel panel-white">
    <div class="row container-no-scroll">
      <div class="col-sm-9 col-xs-9">
        <dl class="dl-horizontal no-margin">
            <dt><p>Context:</p></dt>
            <dd><p><%= @authorisation.scope %></p></dd>
            <% if @viewer_type == 'requester' %>
              <dt><p>Teammate:</p></dt>
              <dd><p><%= @authorisation.granter.first_name %> <%= @authorisation.granter.last_name %>
                (<%= @authorisation.granter.email %>)</p></dd>
            <% else %>
              <dt><p>Teammate:</p></dt>
              <dd><p><%= @authorisation.requester.first_name %> <%= @authorisation.requester.last_name %>
                (<%= @authorisation.requester.email %>)</p></dd>
            <% end %>
        </dl>
      </div>
      <div class="col-sm-3 col-xs-3">
        <% if @viewer_type == 'requester' %>
          <%= link_to 'Ask for new access', authorisation_request_path, class: 'btn btn-primary pull-right' %>
        <% else %>
          <% @authorisation.possible_statuses.each do |possible_status| %>
            <div class="pull-right">
              <%= simple_form_for @authorisation, :url => authorisation_path(@authorisation.token)  do |f| %>
                <%= f.input :status, as: :hidden, :input_html => { value: possible_status } %>
                <% if possible_status == 'granted' %>
                  <%= f.button :submit, "Grant", :class => 'btn-success btn-margin' %>
                <% elsif possible_status == 'revoked' %>
                  <%= f.button :submit, "Revoke", :class => 'btn-warning btn-margin' %>
                <% elsif possible_status == 'denied' %>
                  <%= f.button :submit, "Deny", :class => 'btn-primary btn-margin' %>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <!-- To help see tabs on mobile -->
  <div class="row visible-xs-block">
    <div class="col-xs-12">
      <ul class="nav nav-pills nav-pills">
        <% [{target: 'highlight', display: 'Highlight'}, {target: 'internal', display: 'Internal'},{target: 'all', display: 'All'}].each do |tab| %>
          <li role="presentation" <%= 'class=active' if @tab_filter == tab[:target] %>>
            <a href="<%= authorisation_path(@authorisation.token, tab_filter: tab[:target]) %>"><%= tab[:display] %></a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="row container-scroll">
    <div class="col-sm-2 hidden-xs">
      <div class="panel panel-white">
        <% if @viewer_type == 'requester' %>
          <form class="form-horizontal pull-right" method="get" action="<%= authorisation_path(@authorisation.token) %>">
            <div class="input-group">
              <input type="text" name="search" class="form-control" placeholder="Search for..." value="<%= @search.scope if @search %>">
              <span class="input-group-btn">
                <button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
              </span>
            </div>
          </form>
          <hr/>
        <% end %>
        <ul class="nav nav-pills nav-stacked">
          <li role="presentation" <%= 'class=active' if @tab_filter == 'authorisation_participants' %>>
            <a href="<%= authorisation_path(@authorisation.token, tab_filter: 'authorisation_participants') %>">
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Contacts
            </a>
          </li>
          <li role="presentation" <%= 'class=active' if @tab_filter == 'authorisation_attachments' %>>
            <a href="<%= authorisation_path(@authorisation.token, tab_filter: 'authorisation_attachments') %>">
              <span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span> Attachments
            </a>
          </li>
          <% [{target: 'highlight', display: 'Highlight'}, {target: 'internal', display: 'Internal'},{target: 'all', display: 'All'}].each do |tab| %>
            <li role="presentation" <%= 'class=active' if @tab_filter == tab[:target] %>>
              <a href="<%= authorisation_path(@authorisation.token, tab_filter: tab[:target]) %>">
                <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <%= tab[:display] %>
              </a>
            </li>
          <% end %>
          <% @searches.each do |search| %>
            <li role="presentation" <%= 'class=active' if @search and @search.scope == search.scope %>>
              <a href="<%= authorisation_path(@authorisation.token, search: search.scope) %>">
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                <%= search.scope %>
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <% if @tab_filter == 'authorisation_participants' %>
      <div id="results" class="col-sm-10">
        <% if !@participants_from_scope.empty? %>
          <h2>Participants from the company</h2>
            <%= render partial: 'authorisations/participant', collection: @participants_from_scope %>
        <% end %>
        <h2>All participants to these discussions</h2>
        <table class="table">
          <%= render partial: 'authorisations/participant', collection: @authorisation.participants.uniq %>
        </table>
      </div>
    <% elsif @tab_filter == 'authorisation_attachments' %>
      <div id="results" class="col-sm-10">
        <% @attachments_grouped.each do |index, group| %>
          <%= render partial: 'authorisations/tab/attachment_tab', locals: { file_type: index, attachments: group } %>
        <% end %>
      </div>
    <% else %>
      <div id="results" class="col-sm-5">
        <% if @threads.any? %>
        	<%= render partial: 'authorisations/thread', collection: @threads %>
        <% end %>
      </div>

      <div id="emails" class="col-sm-5 hidden-xs">
      </div>
    <% end %>
  </div>

  <% if @threads %>
    <div id="infinite-scrolling">
      <%= will_paginate @threads %>
    </div>
  <% end %>
</div>