config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :authorisations, only: [:index, :show, :create, :update] do
    get :giving, on: :collection
    post :give, on: :collection
  end
  get 'authorisation/requesting', to: 'authorisations#requesting', as: 'authorisation_request'
  get 'authorisation/grant', to: 'authorisations#granting'
  
  resources :threads, only: [:show]
  post 'threads/update_tags'
  
  resources :attachment, only: [:show] do
  	get :download_inline, on: :collection
  end

  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    resources :users, only: [:index, :show]
    resources :authorisations, only: [:index]
    resources :delegations, only: [:index]
  end

  resources :delegations, only: [:index, :new, :create] do
    get :confirm
    get :revoke
    get :cancel
  end
end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <span id="server-notice" class="hide"><%= notice %></span>
<% end %>
<% if alert %>
  <span id="server-alert" class="hide"><%= alert %></span>
<% end %>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default" id="site-footer">
  <div class="container">
    <ul class="nav navbar-nav navbar-right">
      <% if signed_in? %>
        <li>
          <p class="navbar-text navbar-right">Logged in as <%= current_user.first_name %> <%= current_user.last_name %>
          (<%= current_user.email %>)</p>
        </li>
      <% else %>
        <li>
          <p class="navbar-text navbar-right">- Passiton helps team share context</p>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" id="site-navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="top-navbar">
      <ul class="nav navbar-nav">
        <li class="brand-name"><%= link_to 'Passiton', root_path %>
        <span class="label label-info" id="label-beta">BETA</span>
        </li>
        <% if signed_in? %>
          <li><%= link_to "Get context", authorisations_path %></li>
          <li><%= link_to "Give context", authorisation_grant_path %></li>
          <% if current_user.is_manager %>
            <li><%= link_to "Manage your team", delegations_path %></li>
          <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if signed_in? %>
  	        <li><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
  	    <% else %>
  	        <li class="list-button"><%= link_to "Connect", user_omniauth_authorize_path(:google_oauth2), :class => 'btn btn-primary' %></li>
  	    <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_header_admin.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" id="site-navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar">
          <span class="sr-only">Toggle</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="top-navbar">
      <ul class="nav navbar-nav">
        <% if admin_signed_in? %>
          <li><%= link_to 'Users', admin_users_path %></li>
          <li><%= link_to 'Authorisations', admin_authorisations_path %></li>
          <li><%= link_to 'Delegations', admin_delegations_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if admin_signed_in? %>
  	        <li><%= link_to 'Logout', admin_session_path(current_admin), method: 'delete' %></li>
  	    <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_plugins.html.erb
<script type="text/javascript">
    window.doorbellOptions = {
        appKey: 'E8ZVd5Ht0dB3SS9E667oDJKiaqRjRf0hZqy2ggi3hxsH7xKIvDDmkvU8c2IlwnLZ'
    };
    (function(d, t) {
        var g = d.createElement(t);g.id = 'doorbellScript';g.type = 'text/javascript';g.async = true;g.src = 'https://embed.doorbell.io/button/2643?t='+(new Date().getTime());(d.getElementsByTagName('head')[0]||d.getElementsByTagName('body')[0]).appendChild(g);
    }(document, 'script'));
</script>

<% if we_are_on_production %>
  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-70623371-1', 'auto');
      ga('send', 'pageview');
  </script>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Passiton Admin | <%= yield(:title) %></title>
  <link href='http://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="http://css-spinners.com/css/spinners.css" type="text/css">
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body id= "page-top" class="index">

<%= render 'layouts/header_admin' %>

<div class="container">
  <%= render 'layouts/alerts' %>
	<%= yield %>
	<%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Passiton | <%= yield(:title) %></title>
  <link href='https://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body id= "page-top" class="index backend">

<%= render 'layouts/header' %>

<div class="wrapper-page clearfix">
  <%= render 'layouts/alerts' %>
  <%= render 'delegations/employee_revocation' if current_user and current_user.is_managed? %>
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</div>

<%= render 'layouts/plugins' %>

</body>
</html>

app/views/layouts/marketing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Passiton | <%= yield(:title) %></title>
  <link href='https://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body id= "page-top" class="index">

<%= render 'layouts/header' %>

<div class="<%= 'container' unless @container === false %>">
  <%= render 'layouts/alerts' %>
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</div>

<%= render 'layouts/plugins' %>

</body>
</html>

app/views/layouts/stripped.html.erb
<%= yield %>